name: Simon Stubben
site_title: Simon Stubben - IT Consultancy
description: IT Consultancy. <br><br> <a href="/contact" target="_top">Get in touch</a>.
meta_description: Experienced IT consultant with a strong background in modern IT architectures, data management, and AI-driven process optimization
key_words: ai agents, genai, it architecture, data architecture, software consultancy, software project management, software process optimization, regtech

markdown: kramdown
highlighter: rouge

paginate: 20
baseurl: /
domain_name: 'http://simonstubben.com'
disqus: true
disqus_shortname: 'simonstubben'

# Details for the RSS feed generator
url:            'http://simonstubben.com'
author:         'Simon Stubben'
authorTwitter:  'simonstubben'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

exclude: ['Gemfile', 'Gemfile.lock', 'bin']
